[project]
name = "tetris-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pufferlib>=3.0.0",
    "stable-baselines3>=2.7.0",
]
